FROM python:3.12-slim

WORKDIR /workspace

COPY python/gorz_api ./python/gorz_api

RUN python -m pip install --no-cache-dir -e ./python/gorz_api

EXPOSE 8090

CMD ["uvicorn", "gorz_api.main:app", "--host", "0.0.0.0", "--port", "8090"]

