global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - rules/gozar-profile-api-alerts.yml
  - rules/gozar-android-demo-alerts.yml
  - rules/gozar-safety-alerts.yml

scrape_configs:
  - job_name: profile-api-local
    metrics_path: /metrics
    static_configs:
      - targets:
          - profile-api:8095
  - job_name: gorz-api-local
    metrics_path: /metrics
    static_configs:
      - targets:
          - gorz-api:8090
