import type { MessageDeliveryState } from "../types/chat";
import type {
  ConnectivityConfidenceResult,
  DiagnosticScenarioId,
  SafetyControls,
} from "../types/connectivity";
import type { IncidentClassification, IncidentRecord } from "../types/incident";
import { createId } from "../utils/id";

export interface IncidentRecordInput {
  scenarioId: DiagnosticScenarioId;
  scenarioLabel: string;
  confidence: ConnectivityConfidenceResult;
  messageDeliveryState: MessageDeliveryState;
  safetyControls: SafetyControls;
  notes?: string[];
}

const redactionList = [
  "No real IP address",
  "No phone number",
  "No exact GPS location",
  "No real contact identity",
  "No message plaintext",
  "No raw message content",
  "No device identifier",
];

export function deriveIncidentClassification(
  scenarioId: DiagnosticScenarioId,
  confidence: ConnectivityConfidenceResult,
): IncidentClassification {
  if (scenarioId === "domestic_only_connectivity") {
    return "domestic_only_possible";
  }

  if (scenarioId === "general_outage") {
    return "general_outage_possible";
  }

  if (scenarioId === "low_evidence_inconclusive") {
    return "inconclusive";
  }

  if (
    scenarioId === "app_relay_blocked" ||
    scenarioId === "dns_interference" ||
    scenarioId === "tls_handshake_failure" ||
    scenarioId === "application_delivery_failure"
  ) {
    return "selective_blocking_possible";
  }

  if (confidence.classification === "selective_blocking_or_domestic_only_possible") {
    return "selective_blocking_possible";
  }

  return confidence.classification;
}

export function createIncidentRecord(input: IncidentRecordInput, generatedAt = new Date().toISOString()): IncidentRecord {
  const endedAt = generatedAt;
  const startedAt = new Date(Date.parse(generatedAt) - 10 * 60_000).toISOString();

  return {
    incidentId: createId("incident"),
    appName: "Gorz",
    generatedAt,
    timeWindow: {
      startedAt,
      endedAt,
    },
    scenario: input.scenarioLabel,
    classification: deriveIncidentClassification(input.scenarioId, input.confidence),
    confidenceScore: input.confidence.overallScore,
    layerScores: input.confidence.layerScores,
    evidenceSummary: [
      input.confidence.explanation,
      "Evidence is generated by a local mock simulator for this proof of concept.",
      "Encrypted message content and contact identity are intentionally excluded.",
    ],
    messageDeliveryState: input.messageDeliveryState,
    safetyControls: input.safetyControls,
    redactions: redactionList,
    notes: input.notes ?? ["Simulated PoC data only."],
  };
}

export function serializeIncidentRecord(record: IncidentRecord): string {
  return JSON.stringify(record, null, 2);
}
