apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../namespace.yaml
  - ../../profile-api-deployment.yaml
  - ../../profile-api-service.yaml
  - ../../gorz-api-deployment.yaml
  - ../../gorz-api-service.yaml
  - ../../observability-configmap.yaml
  - ../../prometheus-rules.yaml
  - ../../grafana-dashboard-configmap.yaml
  - ../../siem-detection-rules-configmap.yaml
  - ../../llm-incident-summary-job.yaml
  - ../../networkpolicy.yaml
nameSuffix: -demo
labels:
  - pairs:
      gozar.pirbod.com/environment: demo
