apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - control-plane.yaml
  - gateway.yaml
  - relay.yaml
  - networkpolicy.yaml
commonLabels:
  app.kubernetes.io/managed-by: kustomize
